version: '3.8'
services:
    db:
        image: postgres:13.2-alpine
        restart: always
        container_name: db
        environment:
            POSTGRES_DB: technical
            POSTGRES_USER: technical
            POSTGRES_PASSWORD: technical
        ports:
            - 5432:5432
        volumes:
            - ./db/scripts:/docker-entrypoint-initdb.d
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "technical", "-U", "technical" ]
            interval: 30s
            timeout: 5s
            retries: 5
    server:
        build: ./server
        restart: always
        container_name: server
        depends_on:
            db:
              condition: service_healthy
        ports:
            - 3001:3001
        volumes:
            - ./server/src:/server/src
        command: >
            /bin/sh -c "npm run migration
            && npm run start:dev"
    web:
        build: ./web
        restart: always
        container_name: web
        depends_on:
            db:
              condition: service_healthy
            server:
              condition: service_started
        ports:
            - 3000:3000
        volumes:
            - ./web/src:/web/src